# Generated by Django 6.1.1 on 2026-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_available_days_doctor_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
