# Generated by Django 6.1.1 on 2026-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_appointment_number_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
