# Generated by Django 6.1.1 on 2026-09-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment_medical_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
